// <auto-generated />
namespace MiGitMvc1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_model_date_toStrings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_model_date_toStrings));
        
        string IMigrationMetadata.Id
        {
            get { return "202103172030506_change_model_date_toStrings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
